theme:
  name: material
  favicon: images/logo/favicon.ico
  logo: images/logo/logo-white.svg
  palette:
    scheme: ai4ec
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  language: zh

site_name: 嘉庚智算用户手册
site_url: https://ai4ec.ikkem.com/ikkem-hpc/doc
repo_url: https://github.com/chenggroup/ikkem-hpc-manual
repo_name: chenggroup/ikkem-hpc-manual
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/solid/globe
      link: http://ai4ec.ikkem.com
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 用户手册:
    - 首页: index.md
    - 平台概况和介绍:
      - introduction/index.md
      - 分区规则和收费标准: introduction/partition.md
      - 开户流程: introduction/register.md
      - 重大更新公告: introduction/updates.md
    - 使用指南:
      - 快速上手: usage/quick-start.md
      - 用户登录与文件传输: usage/login.md
      - 应用软件: 
        - usage/apps/index.md
        - usage/apps/abaqus.md
        - usage/apps/amber.md
        - usage/apps/comsol.md
        - usage/apps/cp2k.md
        - usage/apps/gromacs.md
        - usage/apps/gaussian.md
        - usage/apps/lammps.md
        - usage/apps/matlab.md
        - usage/apps/orca.md
        - usage/apps/pytorch.md
        - usage/apps/vasp.md
      - 嘉庚智算中心服务门户: usage/scow.md
      - 应用程序的编译与安装: usage/compile-install.md
    - Slurm作业调度系统:
      - slurm/index.md
      - slurm/basic.md
      - slurm/sinfo.md
      - slurm/squeue.md
      - slurm/partition.md
      - slurm/node.md
      - slurm/job.md
      - slurm/qos.md
      - slurm/submission.md
      - slurm/srun.md
      - slurm/sbatch.md
      - slurm/salloc.md
      - slurm/sbcast.md
      - slurm/sattach.md
      - slurm/sacct.md
      - slurm/others.md
    - 注意事项: information/notes.md
    - 故障排查: information/troubleshooting.md
    - 常见问题: information/faq.md
    - 资料下载: information/download.md
    - 视频教程: information/tutorial.md
  - 新闻公告:
    - blog/index.md