theme:
  name: material
  favicon: favicon.ico
  #logo: images/archer2_white_transparent.png
  palette:
    primary: custom
  features:
    - navigation.path
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github

site_name: 嘉庚智算用户手册
site_url: https://ai4ec.ikkem.com/ikkem-hpc/doc
repo_url: https://github.com/chenggroup/ikkem-hpc-manual
repo_name: hpc-ops/hpc-manual
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/solid/globe
      link: http://ai4ec.ikkem.com

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: index.md
  - 简介:
    - 平台资源: introduction/index.md
    - 重大更新公告: introduction/updates.md
    - 开户流程: introduction/register.md
  - 使用指南:
    - 用户登录与文件传输: usage/login.md
    - 应用软件使用及作业提交: usage/app.md
    - 分区规则和收费标准: usage/partition.md
    - SCOW 算力平台: usage/scow.md
    - 应用程序的编译与安装: usage/compile-install.md
  - Slurm作业调度系统:
    - slurm/index.md
    - slurm/basic.md
    - slurm/sinfo.md
    - slurm/squeue.md
    - slurm/partition.md
    - slurm/node.md
    - slurm/job.md
    - slurm/qos.md
    - slurm/submission.md
    - slurm/srun.md
    - slurm/sbatch.md
    - slurm/salloc.md
    - slurm/sbcast.md
    - slurm/sattach.md
    - slurm/sacct.md
    - slurm/others.md
  - 注意事项: information/notes.md
  - 故障排查: information/troubleshooting.md
  - 常见问题: information/faq.md